name: Publish Documents

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies for Building Documentation
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Build Documentation Site
        run: mkdocs build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Documentation Site
        id: deployment
        uses: actions/deploy-pages@v4
